---
######## DOCKER INSTALL ######## 
- name: 'Adicionando pacotes' 
  yum: 
    name: 'yum-utils'
    state: latest
  become: yes

- name: 'Adicionando repo Docker'
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes

- name: 'Instalando o Docker e suas dependencias' 
  yum: 
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
    state: latest
  become: yes

- name: 'Iniciando o serviço Docker'
  service: 
    name: docker
    state: started
  become: yes

- name: "Adicionando user {{ ansible_env['USER'] }} ao grupo docker"
  when: ansible_env.USER != "root"
  user:
    name: "{{ ansible_env['USER'] }}"
    comment: default user
    groups: 
      - docker 
    state: present
  become: yes


