---
# - hosts: master
#   roles: 
#     - docker 
#     - docker-compose 
- hosts: rhel8
  # tasks:
  #   - name: "teste"
  #     ansible.builtin.debug:
  #       msg: "{{ ansible_env['USER'] }}"
  roles:
    - customizations
    - updates 
    - docker
    - docker-compose
    - virtualbox
    - minikube
    - kubernetes
    - neofetch