---
# - hosts: master
#   roles: 
#     - docker 
#     - docker-compose 
- hosts: rhel8
  # tasks:
    # - name: "teste"
    #   when: ansible_env.USER == "root"
    #   ansible.builtin.debug:
    #     msg: "{{ ansible_env['USER'] }}"


  roles:
    - customizations
    - docker
    - docker-compose
    - virtualbox
    - minikube
    - kubernetes
    - neofetch
    - neovim
    - tmux