---
# - hosts: master
#   roles: 
#     - docker 
#     - docker-compose 
- hosts: rhel8
  roles:
    - customizations
    - updates 
    - docker
    - docker-compose
    - virtualbox
    - minikube
    - kubernetes
    - neofetch