---
######## VIRTUALBOX INSTALL ######## 
- name: "Adicionando Docker repo"
  get_url:
    url: https://download.virtualbox.org/virtualbox/rpm/el/virtualbox.repo
    dest: /etc/yum.repos.d/virtualbox.repo
  become: yes

- name: "Importanto rpm key"
  rpm_key:
    state: present
    key: https://www.virtualbox.org/download/oracle_vbox.asc
  become: yes

- name: 'Habilitando o Epel'
  dnf: 
    name: epel-release
    state: latest
  become: yes

- name: 'Instalando dependencias'
  dnf: 
    name: ["binutils", "kernel-devel", "kernel-headers", "libgomp", "make", "patch", "gcc", "glibc-headers", "glibc-devel", "dkms"]
    state: latest
  become: yes

- name: 'Instalando VBox'
  dnf: 
    name: VirtualBox-6.0
    state: latest
  become: yes

